### ISSUE TITLE
sonic_db_wait doesn't work as expected

### ISSUE THREAD

**Issue by shuaishang** [sonic-net/sonic-wpa-supplicant#53]
sonic_db_wait was designed to wait "table"+"key" with "value_pairs".
But the following code only select the "table" and compare "value_pairs", it doesn't check "key".

https://github.com/Azure/sonic-wpa-supplicant/blob/64caafe3833914f4838fa2e2db290ad676ad8dda/src/drivers/sonic_operators.cpp#L316-L341

For example, when enable MACSec for port Ethernet1, the function "macsec_sonic_macsec_init" will wait STATE_MACSEC_PORT_TABLE_NAME for key "Ethernet1".
But if the state db STATE_MACSEC_PORT_TABLE_NAME was inserted with other key "Ethernet2", the above waiting for "Ethernet1"will finish and return success.

**Comment by shuaishang** [comment]
@Pterosaur could you pls help to have a look?

**Comment by Pterosaur** [comment]
Fixed
